data <- read.csv('~/Downloads/household_power_consumption.txt', sep = ";" , header = TRUE, as.is = TRUE);
data[,1] <- as.Date(data[,1], format = "%d/%m/%Y")
mydates <- as.Date(c("2007-02-01", "2007-02-02"))
data_1 <- subset(data, data$Date %in% mydates)
data_1$Global_active_power<- as.numeric(data_1$Global_active_power, col = 'orange')
data_1$Time<-as.Date(strptime(data_1$Time, format = "%H:%M:%S"))
data_1$Sub_metering_1 = as.numeric(data_1$Sub_metering_1)
data_1$Sub_metering_2 = as.numeric(data_1$Sub_metering_2)
data_1$Sub_metering_3 = as.numeric(data_1$Sub_metering_3)
x11()
par(mfrow = c(2,2))
plot(data_2$Global_active_power, xaxt = "n", type = "l", ylab = "Global Active Power", xlab = "")
axis(1, at=c(1,length(data_1$Global_active_power)/2,length(data_1$Global_active_power) ), labels=c("Thu", "Fri", "Sat"))

plot(data_2$Voltage, xaxt = "n", type = "l", ylab = "Voltage", xlab = "datetime")
axis(1, at=c(1,length(data_1$Global_active_power)/2,length(data_1$Global_active_power) ), labels=c("Thu", "Fri", "Sat"))

plot(x = 1:length(data_1$Sub_metering_1), y = data_1$Sub_metering_1, xaxt = "n", type = "l", ylab = "Energy Sub Metering", xlab = "")
lines(x = 1:length(data_1$Sub_metering_2), y = data_1$Sub_metering_2, xaxt = "n", type = "l", col = 'red')
lines(x = 1:length(data_1$Sub_metering_3), y = data_1$Sub_metering_3, xaxt = "n", type = "l", col = 'blue')
axis(1, at=c(1,length(data_1$Global_active_power)/2,length(data_1$Global_active_power) ), labels=c("Thu", "Fri", "Sat"))
legend('topright',c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty = c(1,1,1),col=c('black','red','blue'),bty ="n")
plot(data_2$Global_reactive_power, xaxt = "n", type = "l", ylab = "Global_reactive_power", xlab = "datetime")
axis(1, at=c(1,length(data_1$Global_active_power)/2,length(data_1$Global_active_power) ), labels=c("Thu", "Fri", "Sat"))

dev.copy(png, file='plot4.png')
dev.off()